/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Director_General;

/**
 *
 * @author Alejandro
 */
public class NuevoTecnico extends javax.swing.JFrame {

    /**
     * Creates new form NuevoTecnico
     */
    public NuevoTecnico() {
        initComponents();
        this.setSize(450, 480); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBRegistrarTecnico = new javax.swing.JLabel();
        JLBNombre = new javax.swing.JLabel();
        JTFNombre = new javax.swing.JTextField();
        JLBApellido = new javax.swing.JLabel();
        JTFApellido = new javax.swing.JTextField();
        JLBATelefono = new javax.swing.JLabel();
        JTFTelefono = new javax.swing.JTextField();
        JLBCorreo = new javax.swing.JLabel();
        JTFCorreo = new javax.swing.JTextField();
        JLBEspecialidad = new javax.swing.JLabel();
        JCBEspecialidades = new javax.swing.JComboBox<>();
        JBNGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBRegistrarTecnico.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBRegistrarTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBRegistrarTecnico.setText("Registrar técnico:");
        getContentPane().add(JLBRegistrarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        JLBNombre.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre.setForeground(new java.awt.Color(102, 102, 102));
        JLBNombre.setText("Nombre (s)");
        getContentPane().add(JLBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 30));

        JTFNombre.setFont(new java.awt.Font("Montserrat ExtraLight", 1, 12)); // NOI18N
        JTFNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNombre.setText("Nombre (s)");
        JTFNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(JTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 310, 30));

        JLBApellido.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBApellido.setForeground(new java.awt.Color(102, 102, 102));
        JLBApellido.setText("Apellido (s)");
        getContentPane().add(JLBApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 30));

        JTFApellido.setFont(new java.awt.Font("Montserrat ExtraLight", 1, 12)); // NOI18N
        JTFApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFApellido.setText("Apellido (s)");
        JTFApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(JTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 310, 30));

        JLBATelefono.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBATelefono.setForeground(new java.awt.Color(102, 102, 102));
        JLBATelefono.setText("Telefono");
        getContentPane().add(JLBATelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 30));

        JTFTelefono.setFont(new java.awt.Font("Montserrat ExtraLight", 1, 12)); // NOI18N
        JTFTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono.setText("Telefono");
        JTFTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(JTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 310, 30));

        JLBCorreo.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBCorreo.setForeground(new java.awt.Color(102, 102, 102));
        JLBCorreo.setText("Correo");
        getContentPane().add(JLBCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, 30));

        JTFCorreo.setFont(new java.awt.Font("Montserrat ExtraLight", 1, 12)); // NOI18N
        JTFCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo.setText("Correo");
        JTFCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(JTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 310, 30));

        JLBEspecialidad.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBEspecialidad.setForeground(new java.awt.Color(102, 102, 102));
        JLBEspecialidad.setText("Especialidad");
        getContentPane().add(JLBEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 100, 30));

        JCBEspecialidades.setFont(new java.awt.Font("Montserrat ExtraLight", 1, 12)); // NOI18N
        JCBEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soporte técnico general", "Soporte de redes", "Soporte de impresoras", "Soporte de portatiles", "Soporte de equipos", "Cableado estructurado" }));
        JCBEspecialidades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JCBEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(JCBEspecialidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 210, 30));

        JBNGuardar.setBackground(new java.awt.Color(0, 165, 104));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(JBNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 102, 42));

        jButton1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 69, 29));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBEspecialidadesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoTecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBNGuardar;
    private javax.swing.JComboBox<String> JCBEspecialidades;
    private javax.swing.JLabel JLBATelefono;
    private javax.swing.JLabel JLBApellido;
    private javax.swing.JLabel JLBCorreo;
    private javax.swing.JLabel JLBEspecialidad;
    private javax.swing.JLabel JLBNombre;
    private javax.swing.JLabel JLBRegistrarTecnico;
    private javax.swing.JTextField JTFApellido;
    private javax.swing.JTextField JTFCorreo;
    private javax.swing.JTextField JTFNombre;
    private javax.swing.JTextField JTFTelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
