/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supervisor_Tecnico;

/**
 *
 * @author Alejandro
 */
public class MenuSupervisorTecnico extends javax.swing.JFrame {

    /**
     * Creates new form MenuSupervisorTecnico
     */
    public MenuSupervisorTecnico() {
        initComponents();
        JMBSupervisorTecnico.add(javax.swing.Box.createHorizontalGlue(), 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBBienvenido = new javax.swing.JLabel();
        JLBSupervisorTecnico = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JMBSupervisorTecnico = new javax.swing.JMenuBar();
        JMNSTTickets = new javax.swing.JMenu();
        JMINuevoTicket = new javax.swing.JMenuItem();
        JMIAsignarTicket = new javax.swing.JMenuItem();
        JMIEditarTicket = new javax.swing.JMenuItem();
        JMNSTTecnicos = new javax.swing.JMenu();
        JMIEditarTecnico = new javax.swing.JMenuItem();
        JMNSTCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLBBienvenido.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBBienvenido.setText("¡Bienvenido!");

        JLBSupervisorTecnico.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBSupervisorTecnico.setText("Supervisor Técnico");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nuevo Ticke.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Asignar Ticket.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N

        JMBSupervisorTecnico.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        JMNSTTickets.setText("Tickets");

        JMINuevoTicket.setText("Nuevo Ticket");
        JMINuevoTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMINuevoTicketActionPerformed(evt);
            }
        });
        JMNSTTickets.add(JMINuevoTicket);

        JMIAsignarTicket.setText("Asignar Ticket");
        JMNSTTickets.add(JMIAsignarTicket);

        JMIEditarTicket.setText("Editar Ticket");
        JMNSTTickets.add(JMIEditarTicket);

        JMBSupervisorTecnico.add(JMNSTTickets);

        JMNSTTecnicos.setText("Técnicos");

        JMIEditarTecnico.setText("Editar Técnico");
        JMNSTTecnicos.add(JMIEditarTecnico);

        JMBSupervisorTecnico.add(JMNSTTecnicos);

        JMNSTCerrarSesion.setText("Cerrar Sesión");
        JMBSupervisorTecnico.add(JMNSTCerrarSesion);

        setJMenuBar(JMBSupervisorTecnico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLBBienvenido)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLBSupervisorTecnico)
                        .addGap(108, 108, 108))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton1)
                        .addGap(56, 56, 56)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JLBBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBSupervisorTecnico)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMINuevoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMINuevoTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMINuevoTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisorTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisorTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisorTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisorTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSupervisorTecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBBienvenido;
    private javax.swing.JLabel JLBSupervisorTecnico;
    private javax.swing.JMenuBar JMBSupervisorTecnico;
    private javax.swing.JMenuItem JMIAsignarTicket;
    private javax.swing.JMenuItem JMIEditarTecnico;
    private javax.swing.JMenuItem JMIEditarTicket;
    private javax.swing.JMenuItem JMINuevoTicket;
    private javax.swing.JMenu JMNSTCerrarSesion;
    private javax.swing.JMenu JMNSTTecnicos;
    private javax.swing.JMenu JMNSTTickets;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
