/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supervisor_Tecnico;

/**
 *
 * @author Alejandro
 */
public class ModificarTicket2 extends javax.swing.JFrame {

    /**
     * Creates new form ModificarTicket2
     */
    public ModificarTicket2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBDescripcion = new javax.swing.JLabel();
        JTADescripcion = new javax.swing.JTextField();
        JLBDescripcion3 = new javax.swing.JLabel();
        JCBTecnico = new javax.swing.JComboBox<>();
        JBNGuardar = new javax.swing.JButton();
        JLBLogo = new javax.swing.JLabel();
        JLBAsignarTecnico = new javax.swing.JLabel();
        JBNCancelar = new javax.swing.JButton();
        JLBDescripcion1 = new javax.swing.JLabel();
        JTFEmpresa = new javax.swing.JTextField();
        JLBDescripcion2 = new javax.swing.JLabel();
        JTFTipo = new javax.swing.JTextField();
        JLBDescripcion4 = new javax.swing.JLabel();
        JCBUsuario = new javax.swing.JComboBox<>();
        JCBFinalizado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLBDescripcion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBDescripcion.setText("Detalles del ticket:");

        JTADescripcion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JTADescripcion.setText("Descripción de los servicios a realizar y detalles puntuales");
        JTADescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        JLBDescripcion3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBDescripcion3.setText("Técnico");

        JCBTecnico.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JCBTecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascencio", " " }));
        JCBTecnico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        JCBTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBTecnicoActionPerformed(evt);
            }
        });

        JBNGuardar.setBackground(new java.awt.Color(39, 174, 96));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBNGuardar.setOpaque(true);
        JBNGuardar.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarActionPerformed(evt);
            }
        });

        JLBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N

        JLBAsignarTecnico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JLBAsignarTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBAsignarTecnico.setText("Editar Ticket");

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });

        JLBDescripcion1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBDescripcion1.setText("Solicita: ");

        JTFEmpresa.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JTFEmpresa.setText("Macias y Aso");
        JTFEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        JTFEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEmpresaActionPerformed(evt);
            }
        });

        JLBDescripcion2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBDescripcion2.setText("Modalidad:");

        JTFTipo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JTFTipo.setText("Remoto");
        JTFTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        JTFTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTipoActionPerformed(evt);
            }
        });

        JLBDescripcion4.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBDescripcion4.setText("Usuario");

        JCBUsuario.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JCBUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maldonado" }));
        JCBUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        JCBUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBUsuarioActionPerformed(evt);
            }
        });

        JCBFinalizado.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JCBFinalizado.setText("¿Ticket Finalizado?");
        JCBFinalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBFinalizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLBLogo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBNCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(JBNGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(JLBDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(JLBDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLBDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JTFEmpresa)
                                            .addComponent(JCBTecnico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLBDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLBDescripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JCBUsuario, 0, 1, Short.MAX_VALUE)
                                            .addComponent(JTFTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(JLBAsignarTecnico)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JTADescripcion)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JCBFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JLBAsignarTecnico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBDescripcion1)
                    .addComponent(JTFEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBDescripcion2)
                    .addComponent(JTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBDescripcion3)
                    .addComponent(JCBTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBDescripcion4)
                    .addComponent(JCBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JLBDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTADescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JCBFinalizado)
                        .addGap(14, 14, 14)
                        .addComponent(JBNGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(JBNCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addComponent(JLBLogo))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBTecnicoActionPerformed

    private void JBNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNGuardarActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JTFTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFTipoActionPerformed

    private void JTFEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFEmpresaActionPerformed

    private void JCBUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBUsuarioActionPerformed

    private void JCBFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBFinalizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBFinalizadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTicket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTicket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTicket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTicket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTicket2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBNCancelar;
    private javax.swing.JButton JBNGuardar;
    private javax.swing.JCheckBox JCBFinalizado;
    private javax.swing.JComboBox<String> JCBTecnico;
    private javax.swing.JComboBox<String> JCBUsuario;
    private javax.swing.JLabel JLBAsignarTecnico;
    private javax.swing.JLabel JLBDescripcion;
    private javax.swing.JLabel JLBDescripcion1;
    private javax.swing.JLabel JLBDescripcion2;
    private javax.swing.JLabel JLBDescripcion3;
    private javax.swing.JLabel JLBDescripcion4;
    private javax.swing.JLabel JLBLogo;
    private javax.swing.JTextField JTADescripcion;
    private javax.swing.JTextField JTFEmpresa;
    private javax.swing.JTextField JTFTipo;
    // End of variables declaration//GEN-END:variables
}
