/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Polizas;

/**
 *
 * @author glomy
 */
public class Nuevo_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_Usuario
     */
    public Nuevo_Usuario() {
        initComponents();
        this.setSize(450, 450); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloNU = new javax.swing.JLabel();
        lblInstruccionesNU = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbClientesNU = new javax.swing.JComboBox<>();
        btnSiguienteNU = new javax.swing.JButton();
        btnCancelarNU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(450, 450));
        setResizable(false);

        lblTituloNU.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTituloNU.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloNU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloNU.setText("Nuevo Usuario");

        lblInstruccionesNU.setBackground(new java.awt.Color(255, 255, 255));
        lblInstruccionesNU.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblInstruccionesNU.setForeground(new java.awt.Color(153, 153, 153));
        lblInstruccionesNU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruccionesNU.setText("<html><div style='text-align: center;'>Seleccione al cliente que<br>autoriza el uso<br>de los servicios de la<br>póliza al usuario</div></html>");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETS MINI2.png"))); // NOI18N

        cmbClientesNU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbClientesNU.setForeground(new java.awt.Color(153, 153, 153));
        cmbClientesNU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes registrados..." }));
        cmbClientesNU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSiguienteNU.setBackground(new java.awt.Color(0, 153, 102));
        btnSiguienteNU.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSiguienteNU.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteNU.setText("Siguiente");
        btnSiguienteNU.setBorderPainted(false);
        btnSiguienteNU.setFocusPainted(false);

        btnCancelarNU.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelarNU.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelarNU.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarNU.setText("Cancelar");
        btnCancelarNU.setBorderPainted(false);
        btnCancelarNU.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addComponent(btnSiguienteNU, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnCancelarNU))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloNU, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstruccionesNU, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbClientesNU, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloNU)
                .addGap(32, 32, 32)
                .addComponent(lblInstruccionesNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(cmbClientesNU, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addComponent(btnSiguienteNU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnCancelarNU))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarNU;
    private javax.swing.JButton btnSiguienteNU;
    private javax.swing.JComboBox<String> cmbClientesNU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInstruccionesNU;
    private javax.swing.JLabel lblTituloNU;
    // End of variables declaration//GEN-END:variables
}
