/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Alejandro
 */
public class NuevoTicket extends javax.swing.JFrame {

    /**
     * Creates new form NuevoTicket
     */
    public NuevoTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBGTipoServicio = new javax.swing.ButtonGroup();
        JLBNuevoTicket = new javax.swing.JLabel();
        JLBDescripcion1 = new javax.swing.JLabel();
        JLBDescripcion2 = new javax.swing.JLabel();
        JLBDescripcion3 = new javax.swing.JLabel();
        JTFNumeroDePoliza = new javax.swing.JTextField();
        JLBDescripcion4 = new javax.swing.JLabel();
        JLBAsesoria = new javax.swing.JLabel();
        JLBRemoto = new javax.swing.JLabel();
        JLBPresencial = new javax.swing.JLabel();
        JRBAsesoria = new javax.swing.JRadioButton();
        JRBRemoto = new javax.swing.JRadioButton();
        JRBPresencial = new javax.swing.JRadioButton();
        JBNGuardarTicket = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();
        JLBLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLBNuevoTicket.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBNuevoTicket.setText("Nuevo Ticket");

        JLBDescripcion1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBDescripcion1.setText("Ingrese el numero de póliza");

        JLBDescripcion2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBDescripcion2.setText("del solicitante y modalidad");

        JLBDescripcion3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBDescripcion3.setText("de atención requerida");

        JTFNumeroDePoliza.setFont(new java.awt.Font("Montserrat ExtraLight", 0, 14)); // NOI18N
        JTFNumeroDePoliza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNumeroDePoliza.setText("Numero de poliza");
        JTFNumeroDePoliza.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        JTFNumeroDePoliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNumeroDePolizaActionPerformed(evt);
            }
        });

        JLBDescripcion4.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBDescripcion4.setText("Tipo de servicio");

        JLBAsesoria.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBAsesoria.setText("Asesoria");

        JLBRemoto.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBRemoto.setText("Remoto");

        JLBPresencial.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLBPresencial.setText("Presencial");

        JBGTipoServicio.add(JRBAsesoria);
        JRBAsesoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBAsesoriaActionPerformed(evt);
            }
        });

        JBGTipoServicio.add(JRBRemoto);

        JBGTipoServicio.add(JRBPresencial);

        JBNGuardarTicket.setBackground(new java.awt.Color(0, 165, 104));
        JBNGuardarTicket.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JBNGuardarTicket.setText("Guardar");
        JBNGuardarTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        JLBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLBDescripcion2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(JLBNuevoTicket))
                            .addComponent(JLBDescripcion1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(JLBDescripcion3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(JTFNumeroDePoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(JLBAsesoria)
                                            .addComponent(JLBRemoto)))
                                    .addComponent(JLBPresencial, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JRBRemoto)
                                    .addComponent(JRBPresencial)
                                    .addComponent(JRBAsesoria)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(JLBDescripcion4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBNCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBNGuardarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLBLogo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLBNuevoTicket)
                        .addGap(26, 26, 26)
                        .addComponent(JLBDescripcion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLBDescripcion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLBDescripcion3)
                        .addGap(18, 18, 18)
                        .addComponent(JTFNumeroDePoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(JLBDescripcion4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRBAsesoria)
                            .addComponent(JLBAsesoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLBRemoto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JRBRemoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JRBPresencial)
                                    .addComponent(JLBPresencial))))
                        .addGap(18, 18, 18)
                        .addComponent(JBNGuardarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBNCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNumeroDePolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNumeroDePolizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNumeroDePolizaActionPerformed

    private void JRBAsesoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBAsesoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBAsesoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JBGTipoServicio;
    private javax.swing.JButton JBNCancelar;
    private javax.swing.JButton JBNGuardarTicket;
    private javax.swing.JLabel JLBAsesoria;
    private javax.swing.JLabel JLBDescripcion1;
    private javax.swing.JLabel JLBDescripcion2;
    private javax.swing.JLabel JLBDescripcion3;
    private javax.swing.JLabel JLBDescripcion4;
    private javax.swing.JLabel JLBLogo;
    private javax.swing.JLabel JLBNuevoTicket;
    private javax.swing.JLabel JLBPresencial;
    private javax.swing.JLabel JLBRemoto;
    private javax.swing.JRadioButton JRBAsesoria;
    private javax.swing.JRadioButton JRBPresencial;
    private javax.swing.JRadioButton JRBRemoto;
    private javax.swing.JTextField JTFNumeroDePoliza;
    // End of variables declaration//GEN-END:variables
}
