/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tecnico;

/**
 *
 * @author suare
 */
public class MisTickets extends javax.swing.JFrame {

    /**
     * Creates new form MisTickets
     */
    public MisTickets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JCBTicketsA = new javax.swing.JComboBox<>();
        JBNSiguienteA = new javax.swing.JButton();
        JLBMisTickets = new javax.swing.JLabel();
        JCBTicketsR = new javax.swing.JComboBox<>();
        JBNSiguienteR = new javax.swing.JButton();
        JCBTicketsP = new javax.swing.JComboBox<>();
        JBNSiguienteP = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();
        JLBLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JCBTicketsA.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        JCBTicketsA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tickets de asesoria", "Ticket", "Ticket", "Ticket" }));
        JCBTicketsA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        JBNSiguienteA.setBackground(new java.awt.Color(39, 174, 96));
        JBNSiguienteA.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteA.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteA.setText("Siguiente");
        JBNSiguienteA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBNSiguienteA.setOpaque(true);
        JBNSiguienteA.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteAActionPerformed(evt);
            }
        });

        JLBMisTickets.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JLBMisTickets.setForeground(new java.awt.Color(102, 102, 102));
        JLBMisTickets.setText("Mis Tickets");

        JCBTicketsR.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        JCBTicketsR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tickets remotos", "Ticket", "Ticket", "Ticket" }));
        JCBTicketsR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        JBNSiguienteR.setBackground(new java.awt.Color(39, 174, 96));
        JBNSiguienteR.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteR.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteR.setText("Siguiente");
        JBNSiguienteR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBNSiguienteR.setOpaque(true);
        JBNSiguienteR.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteRActionPerformed(evt);
            }
        });

        JCBTicketsP.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        JCBTicketsP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tickets presenciales", "Ticket", "Ticket", "Ticket" }));
        JCBTicketsP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        JBNSiguienteP.setBackground(new java.awt.Color(39, 174, 96));
        JBNSiguienteP.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteP.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteP.setText("Siguiente");
        JBNSiguienteP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBNSiguienteP.setOpaque(true);
        JBNSiguienteP.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguientePActionPerformed(evt);
            }
        });

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });

        JLBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JBNSiguienteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JCBTicketsR, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(JBNSiguienteR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(96, 96, 96))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCBTicketsP, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(JBNSiguienteP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addComponent(JLBMisTickets))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(JCBTicketsA, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JLBLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBNCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(JLBMisTickets)
                .addGap(30, 30, 30)
                .addComponent(JCBTicketsA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBNSiguienteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JCBTicketsR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBNSiguienteR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JCBTicketsP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBNSiguienteP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(JBNCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(JLBLogo, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBNSiguienteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteAActionPerformed

    private void JBNSiguienteRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteRActionPerformed

    private void JBNSiguientePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguientePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguientePActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBNCancelar;
    private javax.swing.JButton JBNSiguienteA;
    private javax.swing.JButton JBNSiguienteP;
    private javax.swing.JButton JBNSiguienteR;
    private javax.swing.JComboBox<String> JCBTicketsA;
    private javax.swing.JComboBox<String> JCBTicketsP;
    private javax.swing.JComboBox<String> JCBTicketsR;
    private javax.swing.JLabel JLBLogo;
    private javax.swing.JLabel JLBMisTickets;
    // End of variables declaration//GEN-END:variables
}
